# packages in environment at /home/user/anaconda3/envs/:
#
# Name                    Version                   Build  Channel
dgl                       0.6.0                    pypi_0    pypi
dgl-cuda11.6              0.9.1post1               py39_0    dglteam
dgllife                   0.3.2                    pypi_0    pypi
numpy                     1.24.4                   pypi_0    pypi
bio_embeddings            0.2.2                    pypi_0    pypi
nvidia-cuda-cupti-cu11    11.7.101                 pypi_0    pypi
nvidia-cuda-nvrtc-cu11    11.7.99                  pypi_0    pypi
nvidia-cuda-runtime-cu11  11.7.99                  pypi_0    pypi
pip                       23.3.2                   pypi_0    pypi
python                    3.9.15          hba424b6_0_cpython    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pytorch-lightning         1.8.6                    pypi_0    pypi
pytorch-pretrained-bert   0.6.2                    pypi_0    pypi
pytorch-transformers      1.1.0                    pypi_0    pypi
pandas                    1.5.2            py39h4661b88_0    conda-forge
rdkit                     2022.9.5                 pypi_0    pypi
readline                  8.1.2                h0f457ee_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
scikit-learn              0.24.2                   pypi_0    pypi
scipy                     1.9.3                    pypi_0    pypi
tqdm                      4.64.1                   pypi_0    pypi
torch                     2.0.1                    pypi_0    pypi
torch-cluster             1.6.1+pt20cu117          pypi_0    pypi
torch-geometric           2.3.1                    pypi_0    pypi
torch-scatter             2.1.1+pt20cu117          pypi_0    pypi
torch-sparse              0.6.17+pt20cu117         pypi_0    pypi
torchmetrics              0.11.4                   pypi_0    pypi
torchvision               0.15.2                   pypi_0    pypi
wget                      3.2                      pypi_0    pypi